name: ci-backend-workflow

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  # Setting an environment variable with the value of a configuration variable
  BACKEND_ECR_URL: ${{ vars.BACKEND_ECR_URL }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install the dependencies.
      - run: |
          cd backend && python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      # Run the linter.
      - run: cd backend && pipenv run lint .

      # Send a console message at completion.
      - run: |
          echo "Lint Stage Completed"

  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Install the dependencies.
      - run: |
          cd backend && python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      # Run the linter.
      - run: cd backend && pipenv run test

      # Send a console message at completion.
      - run: |
          echo "Test Stage Completed"

  build:
    needs: [ lint,test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Build Backend
      - name: Build Backend
        run: |
          cd backend && docker build
