name: cd-frontend-workflow

on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on push events to the main branch
  push:
    branches:
      - master
#    paths:
#      - 'frontend/**'

env:
  # Setting an environment variable with the value of a configuration variable
  FRONTEND_ECR_URL: ${{ vars.FRONTEND_ECR_URL }}
  REACT_APP_MOVIE_API_URL: ${{ vars.REACT_APP_MOVIE_API_URL }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      # clear cache
      - run: cd frontend && npm cache clean --force

      # Install the dependencies.
      - run: cd frontend && npm ci

      # Run the linter.
      - run: cd frontend && npm run lint .

      # Send a console message at completion.
      - run: |
          echo "Lint Step Completed"

  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - uses: actions/checkout@v3

      # Set up a Node.js environment using the specified node version.
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      # clear cache
      - run: cd frontend && npm cache clean --force

      # Install the dependencies.
      - run: cd frontend && npm ci

      # Run the tests.
      - run: cd frontend && npm test --passWithNoTests

      # Send a console message at completion.
      - run: |
          echo "Test Step Completed"

  build:
    needs: [ lint,test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend && docker build --build-arg REACT_APP_MOVIE_API_URL=$REACT_APP_MOVIE_API_URL -t $FRONTEND_ECR_URL:$IMAGE_TAG .
          docker push $FRONTEND_ECR_URL:$IMAGE_TAG

  deploy:
    needs: [ lint,test, build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - run: aws eks update-kubeconfig --name cluster

      - name: Deploy Frontend
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd frontend/k8s && kustomize edit set image frontend=$FRONTEND_ECR_URL:$IMAGE_TAG
          kustomize build | kubectl apply -f -

        
